global:
  scrape_interval:     5s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: node-health
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
        - node-exporter:9100
  - job_name: 'plasma-service'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - 'metrics-server:8081'